<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Imagenes\FC27.png" />
    <None Remove="Imagenes\Minecraft.png" />
    <None Remove="Imagenes\Overwatch.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Imagenes\FC27.png" />
    <Resource Include="Imagenes\Minecraft.png" />
    <Resource Include="Imagenes\Overwatch.png" />
  </ItemGroup>

</Project>
